language: python
os: linux
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
script:
  - pip install -e .
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Your encrypted token"
  on:
    tags: true
    branch: master